import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState, SyntheticEvent} from 'react';
import debounce from 'lodash.debounce';

import styles from '../styles/Home.module.css'
import { SidebarMenu } from '../components/sidebar-menu';
import { DriverCard } from '../components/driver-card';
import { Pagination } from '../components/pagination';
import { Driver, DriverServiceResponse, getDrivers, searchDriver } from '../services/drivers';

const DRIVER_PER_PAGE = 5;

interface OnSearchEvent {
  target: HTMLInputElement;
}

const Home: NextPage = () => {
  const [drivers, setDrivers] = useState<Driver[]>([]);
  const [totalPage, setTotalPage] = useState(0);
  const [currentPage, setCurrentPage] = useState(0);

  useEffect(() => {
    const fetchData = async () => {
      const { result, meta } = await getDrivers({ startIndex: 0, limit: DRIVER_PER_PAGE });

      setTotalPage(Math.ceil(meta.total / DRIVER_PER_PAGE));
      setCurrentPage(1);
      setDrivers(result);
    }

    fetchData();
  }, []);

  const searchDriverByName = (query: string) => {
    const fetchData = async () => {
      const { result, meta } = await searchDriver(query, { startIndex: 0, limit: DRIVER_PER_PAGE });

      setTotalPage(Math.ceil(meta.total / DRIVER_PER_PAGE));
      setCurrentPage(1);
      setDrivers(result);
    };

    fetchData();
  };
  const debouncedSearchDriver = debounce(searchDriverByName, 500);

  const handlePageChange = (newPage: number) => {
    const fetchData = async () => {
      const newIndex = (newPage - 1) * DRIVER_PER_PAGE;
      const { result, meta } = await getDrivers({ startIndex: newIndex, limit: DRIVER_PER_PAGE });

      setCurrentPage(newPage);
      setDrivers(result);
    }

    fetchData();
  };

  const handleSearchQueryChange = (ev: OnSearchEvent) => {
    const searchEl: HTMLInputElement = ev.target;
    debouncedSearchDriver(searchEl.value);
  };

  return (
    <div className="grid grid-rows-[auto_1fr_auto] grid-cols-[100%] min-h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-row justify-between">
        <div className="h-16 bg-white text-red-500 flex justify-items-center items-center px-8 py-4">
          <h1 className="font-bold italic text-2xl">Shipper</h1>
        </div>

        <div className="flex-end px-8 flex justify-items-center items-center">
          <h2>Hello, Shipper user</h2>
        </div>
      </header>

      <main className="flex flex-row">
        <div className="sidebar w-2/12 px-8 pt-4">
          <SidebarMenu />
        </div>

        <div className="content bg-gray-100 w-10/12 px-12 py-8">
          <div className="content-header flex flex-row justify-between content-center bg-white px-8 py-4">
            <div className="content-title">
              <p className="uppercase text-4xl text-red-500 font-semibold">Driver Management</p>
              <p className="text-slate-600 text-lg">Data driver yang berkerja dengan anda</p>
            </div>

            <div className="content-toolbar">
              <form className="search-form text-xl flex flex-row gap-x-4">
                <input onChange={handleSearchQueryChange} className="border border-solid border-gray-400 px-4 flex-1" type="text" placeholder="Cari Driver" />
                <button className="bg-red-500 text-slate-100 px-8 py-4  flex-1">Tambah Driver</button>
              </form>
            </div>
          </div>

          <div className="driver-list flex flex-row flex-nowrap gap-x-8 pt-8 pb-4 w-fit max-w-full overflow-x-scroll">
            { drivers.map(driver => (<DriverCard key={driver.email} driver={driver} />)) }
          </div>

          <Pagination
            totalPage={totalPage}
            currentPage={currentPage}
            onChangePage={(pageNum) => handlePageChange(pageNum)}
          />

        </div>
      </main>

      <footer className="h-8">
      </footer>
    </div>
  )
}

export default Home
