import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { SidebarMenu } from '../components/sidebar-menu';

const Home: NextPage = () => {
  return (
    <div className="grid grid-rows-[auto_1fr_auto] grid-cols-[100%] min-h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-row justify-between">
        <div className="h-16 bg-white text-red-500 flex justify-items-center items-center px-8 py-4">
          <h1 className="font-bold italic text-2xl">Shipper</h1>
        </div>

        <div className="flex-end px-8 flex justify-items-center items-center">
          <h2>Hello, Shipper user</h2>
        </div>
      </header>

      <main className="flex flex-row">
        <div className="sidebar w-2/12 px-8">
          <SidebarMenu />
        </div>

        <div className="content bg-gray-100 w-full px-12 py-8">
          <div className="content-header flex flex-row justify-between content-center bg-white px-8 py-4">
            <div className="content-title">
              <p className="uppercase text-4xl text-red-500 font-semibold">Driver Management</p>
              <p className="text-slate-600 text-lg">Data driver yang berkerja dengan anda</p>
            </div>

            <div className="content-toolbar">
              <form className="search-form text-xl flex flex-row gap-x-4">
                <input className="border border-solid border-gray-400 px-4 flex-1" type="text" placeholder="Cari Driver" />
                <button className="bg-red-500 text-slate-400 px-8 py-4  flex-1">Tambah Driver</button>
              </form>
            </div>
          </div>

          <div className="driver-list pt-8">
            <div className="driver-card bg-white w-1/4">
              <div className="driver-card__header flex flex-row justify-between border-b-2 border-solid border-gray-300 px-8 py-4">
                <p>Driver ID : <span className="text-red-500 font-semibold">ID-XYZ99561</span></p>
                <p>...</p>
              </div>

              <div className="driver-card__body flex flex-col gap-2 px-8 py-4">
                <div className="mb-8">
                  <div className="relative h-32 w-32">
                    <Image className="rounded-full" src="/blank-profile-picture.png" alt="driver-picture" layout="fill" />
                  </div>
                </div>

                <div>
                  <p className="text-gray-600">Nama Driver</p>
                  <p className="font-semibold text-lg">First Name, Last Name</p>
                </div>
                <div>
                  <p className="text-gray-600">Nomor Telepon</p>
                  <p className="font-semibold text-lg">Phone Number</p>
                </div>
                <div>
                  <p className="text-gray-600">Email</p>
                  <p className="font-semibold text-lg">Email Address</p>
                </div>
                <div>
                  <p className="text-gray-600">Tanggal Lahir</p>
                  <p className="font-semibold text-lg">DD-MM-YYYY</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer>
        <p>Footer</p>
      </footer>
    </div>
  )
}

export default Home
