import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';

import styles from '../styles/Home.module.css'
import { SidebarMenu } from '../components/sidebar-menu';
import { DriverCard } from '../components/driver-card';
import { Pagination } from '../components/pagination';
import { Driver, getDrivers } from '../services/drivers';

const Home: NextPage = () => {
  const [drivers, setDrivers] = useState<Driver[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const result = await getDrivers();

      setDrivers(result)
    }

    fetchData();
  }, []);

  return (
    <div className="grid grid-rows-[auto_1fr_auto] grid-cols-[100%] min-h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-row justify-between">
        <div className="h-16 bg-white text-red-500 flex justify-items-center items-center px-8 py-4">
          <h1 className="font-bold italic text-2xl">Shipper</h1>
        </div>

        <div className="flex-end px-8 flex justify-items-center items-center">
          <h2>Hello, Shipper user</h2>
        </div>
      </header>

      <main className="flex flex-row">
        <div className="sidebar w-2/12 px-8">
          <SidebarMenu />
        </div>

        <div className="content bg-gray-100 w-10/12 px-12 py-8">
          <div className="content-header flex flex-row justify-between content-center bg-white px-8 py-4">
            <div className="content-title">
              <p className="uppercase text-4xl text-red-500 font-semibold">Driver Management</p>
              <p className="text-slate-600 text-lg">Data driver yang berkerja dengan anda</p>
            </div>

            <div className="content-toolbar">
              <form className="search-form text-xl flex flex-row gap-x-4">
                <input className="border border-solid border-gray-400 px-4 flex-1" type="text" placeholder="Cari Driver" />
                <button className="bg-red-500 text-slate-400 px-8 py-4  flex-1">Tambah Driver</button>
              </form>
            </div>
          </div>

          <div className="driver-list flex flex-row flex-nowrap gap-x-8 pt-8 pb-4 w-fit max-w-full overflow-x-scroll">

            { drivers.slice(5).map(driver => (<DriverCard key={driver.email} driver={driver} />)) }
          </div>

          <Pagination />

        </div>
      </main>

      <footer className="h-8">
      </footer>
    </div>
  )
}

export default Home
